# Generated by Django 4.1.6 on 2024-01-09 13:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about', models.CharField(max_length=140)),
                ('image', models.URLField()),
                ('blog_content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('any_url', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
