# Generated by Django 4.1.6 on 2024-01-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact_school', '0002_blog_carusel_content_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Carusel',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title_type',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='title_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
