# Generated by Django 4.1.6 on 2024-01-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact_school', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='langulages',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
