# Generated by Django 4.1.6 on 2024-01-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact_school', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='quiz_choise_v1',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='content',
            name='quiz_choise_v2',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='content',
            name='quiz_choise_v3',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='content',
            name='quiz_choise_v4',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='content',
            name='quiz_title',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
