# Generated by Django 4.1.6 on 2024-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact_school', '0009_content_quiz_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='quiz_choise_v1_2',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='quiz_choise_v2_2',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='quiz_choise_v3_3',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='quiz_choise_v4_4',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='quiz_choise_v1',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='quiz_choise_v2',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='quiz_choise_v3',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='quiz_choise_v4',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='quiz_title',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='quiz_title2',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
